language: ruby

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE chitter_test;'
  - psql -U postgres -c '\c chitter_test; CREATE TABLE cheeps(id SERIAL PRIMARY KEY, cheep VARCHAR(240));'

script:
  - bundle exec rspec
